### ISSUE TITLE
Funcionalidades

### ISSUE THREAD

**Issue by OsvaldoNeves1** [InfnetDAPB2020T1/ADS2020#4]
Como usuário, ao eu entrar em um estabelecimento, desejo criar uma "sala" onde eu possa registrar minha comanda.
Na sala, eu tenho acesso aos pedidos de quem está na mesa, qual a forma de pagamento sera realizada por cada pessoa, e como serão as subdivisões (ex.: se há algum casal na mesa que vai dividir a conta além das outras pessoas)!

**Comment by marcelovergara-web** [comment]
Funcionalidade sendo tratada por outra issue.
